# Make a suammry table
library(gt)
library(tidyverse)

# Read data
dat <- read_csv("data/summary-table-01-03-2019.csv")

# Create table
gt_table <- gt(tab_header(dat,
              title = "Summary of ImmunoSense Objectives", 
              subtitle = "6th March 2019"))

# Style tables
tab_html <- as_raw_html(gt_table %>% 
        # Rename columns
        cols_label(experiments = "Experiments",
                   treatments = "Treatments",
                   cell_culture = "Cell culture",
                   processing = "Sample preparation",
                   mass_spectrometry = "Mass spectrometry",
                   analysis = "Data Analysis") %>% 
        # NAs
        tab_style(cells_styles(text_color = "grey"),
                  locations = cells_data(columns = 2:5, rows = 1)) %>% 
        tab_style(cells_styles(text_color = "grey"),
                  locations = cells_data(columns = c(2,5), rows = 2)) %>%
        tab_style(cells_styles(text_color = "grey"),
                  locations = cells_data(columns = c(4,5), rows = 3)) %>%
        tab_style(cells_styles(text_color = "grey"),
                  locations = cells_data(columns = c(4,5), rows = 4)) %>%
        tab_style(cells_styles(text_color = "grey"),
                  locations = cells_data(columns = 5, rows = 5)) %>%
        tab_style(cells_styles(text_color = "grey"),
                  locations = cells_data(columns = 3, rows = 9)) %>%
        # DONE
        tab_style(cells_styles(text_color = "blue",text_weight = "bold"),
                  locations = cells_data(columns = 6, rows = 1)) %>% 
        tab_style(cells_styles(text_color = "blue",text_weight = "bold"),
                  locations = cells_data(columns = c(3,4,6), rows = 2)) %>% 
        tab_style(cells_styles(text_color = "blue",text_weight = "bold"),
                  locations = cells_data(columns = c(3,6), rows = 3)) %>% 
        tab_style(cells_styles(text_color = "blue",text_weight = "bold"),
                  locations = cells_data(columns = c(3,6), rows = 4)) %>% 
        tab_style(cells_styles(text_color = "blue",text_weight = "bold"),
                  locations = cells_data(columns = c(3,4,6), rows = 5)) %>% 
        tab_style(cells_styles(text_color = "blue",text_weight = "bold"),
                  locations = cells_data(columns = c(3), rows = 6)) %>% 
        tab_style(cells_styles(text_color = "blue",text_weight = "bold"),
                  locations = cells_data(columns = c(3), rows = 7)) %>% 
        tab_style(cells_styles(text_color = "blue",text_weight = "bold"),
                  locations = cells_data(columns = c(3:5), rows = 8)) %>% 
        # To-do
        tab_style(cells_styles(text_color = "red",text_weight = "bold"),
                  locations = cells_data(columns = c(4:6), rows = 6)) %>%
        tab_style(cells_styles(text_color = "red",text_weight = "bold"),
                  locations = cells_data(columns = c(4:6), rows = 7)) %>%
        tab_style(cells_styles(text_color = "red",text_weight = "bold"),
                  locations = cells_data(columns = c(5:6), rows = 9)) %>%
        # Ongoing
        tab_style(cells_styles(text_color = "orange",text_weight = "bold"),
                  locations = cells_data(columns = c(6), rows = 8)) %>%
        tab_style(cells_styles(text_color = "orange",text_weight = "bold"),
                  locations = cells_data(columns = c(4), rows = 9)) %>%
        # Footnotes
        tab_footnote(footnote = "HaCaT HLA-A2 transfectant generated by Rachel Darley",
                     locations = cells_data(columns = vars(experiments),rows = 2)) %>% 
        tab_footnote(footnote = html("These peptidomes are three new replicates
        performed using Ben Nicholas's improved purification method, and with treatment
        dose at 5 &mu;M treatment. Approx. 4 weeks work to complete."),
        locations = cells_data(columns = vars(experiments),rows = 6:7)) %>% 
        tab_footnote(footnote = html("Four peptides identified from 
                                     original peptidome analysis for clinical assays.
                                     Approx. 2 weeks work to complete."),
                     locations = cells_data(columns = vars(experiments),rows = 9)
        ),
        inline_css = TRUE)

write_file(tab_html,"data/immunosense-summary-table-01-03-2019.html")
