---
title: "ImmunoSense"
author: "Alistair Bailey"
date: "6th March 2019"
output:
  xaringan::moon_reader:
    #seal: false
    css: ["default", "uos-fonts.css","ninjutsu","uos.css","assets/ninpo.css"]
    chakra: libs/remark-latest.min.js
    lib_dir: libs
    nature:
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
      ratio: '16:9'
---

```{r setup, include=FALSE}
options(htmltools.dir.version = FALSE)
library(tidyverse)
library(UpSetR)
library(ggseqlogo)

# Load HaCaT data
dat <- readRDS("data/dat.RDS")

dat_sub <- dat %>% select(peptide,length,exp_name,accession) %>%
  filter(length >= 8 & length <= 15, str_detect(accession,"HUMAN")) %>%
  mutate(exp_type = if_else(str_detect(exp_name,"^C"),
                                         "Control","DNCB"),
         peptide = str_replace_all(peptide,"\\(.*?\\)", ""))

# Transfectant data
# a2_dat <- read_rds("data/a2_dat.RDS") %>% 
#   select(peptide,length,exp_name,accession) %>% 
#   filter(length >= 8 & length <= 15, str_detect(accession,"HUMAN")) %>% 
#   mutate(exp_type = if_else(str_detect(exp_name,"^C"), 
#                                          "Control","DNCB"),
#          peptide = str_replace_all(peptide,"\\(.*?\\)", ""))
# 
a2_dncb_mods <- read_rds("data/a2_dncb_mods.RDS")

wt_logos <- read_rds("data/hacat-wt-pred-logos-dat.rds")
iedb_wt_logos <- read_rds("data/ideb-wt-logos-dat.rds")
ideb_a2_logos <- read_rds("data/iedb-logos-A2.rds")
a2_logos <- read_rds("data/hacat-A2-pred-logos.rds")
# bind_plot <- read_rds("data/hacat_wt_pred_binders_plot.RDS")
# a2_bind_plot <- read_rds("data/hacat_pred_binders_plot.RDS")

glut_sub <- read_rds("data/glut_sub.RDS")
ker_sub <- read_rds("data/ker_sub.RDS")

# rini_df <- read_rds("data/rini_df.RDS")
# ker_df <- read_rds("data/ker_df.RDS")

cell_viability <- read_rds("data/cell-viability-output-20-12-2018.rds")
# Marine-1, Horizon-1, Horizon-3, Marine-2, Horizon-2
my_cols <- c("#005C84","#FCBC00","#E73037","#74C9E5","#EF7D00")
```

class: center,middle

```{r summary-table,echo=FALSE}
htmltools::includeHTML("data/immunosense-summary-table-01-03-2019.html")
```

---

layout: false
class: split-two 

.column.inverse[.content.center.vmiddle[

Number of peptide N-mers, n = 6

```{r, fig.retina=4,echo=FALSE, cache=TRUE}
dat_sub %>% 
  select(length, exp_type, exp_name) %>% 
  group_by(length, exp_name) %>% 
  mutate(n_peps = n()) %>% 
  ungroup() %>% 
  distinct() %>% 
  group_by(length,exp_type) %>% 
  summarise(mean_peps = mean(n_peps), sqn = sqrt(n()),  sem = sd(n_peps)/sqn) %>%
  ggplot(aes(x = length, y = mean_peps,fill = exp_type)) +
  geom_bar(stat='identity') +
  geom_errorbar(aes(ymin=mean_peps-sem, ymax=mean_peps+sem),
                width=.2) +
  scale_x_continuous(breaks=seq(8, 15, 1)) +
  theme_minimal(base_size = 16) +
  theme(legend.position = "") +
  xlab("Peptide length") +
  ylab("Number of peptides") +
  #scale_fill_brewer(palette="Set1") +
  scale_fill_manual(values = my_cols[c(1,3)]) +
  facet_wrap(~ exp_type)
```

]]

.column.inverse[.content.center.vmiddle[

Percentage of peptide N-mers, n = 6

```{r, fig.retina=4,echo=FALSE, cache=TRUE}
dat_sub %>% 
  select(length, exp_type, exp_name) %>% 
  group_by(exp_name, length) %>% 
  summarise(n = n()) %>% 
  mutate(f_peps = n/sum(n), 
         exp_type = if_else(str_detect(exp_name,"^C"), 
                                         "Control","DNCB")) %>% 
  ungroup() %>%
  distinct() %>% 
  group_by(exp_type,length) %>% 
  summarise(mean_peps = mean(f_peps), sqn = sqrt(n()),  sem = sd(f_peps)/sqn) %>%
  ggplot(aes(x = length, y = mean_peps,fill = exp_type)) +
  geom_bar(stat='identity') +
  geom_errorbar(aes(ymin=mean_peps-sem, ymax=mean_peps+sem),
                width=.2) +
  scale_x_continuous(breaks=seq(8, 15, 1)) +
          scale_y_continuous(labels=scales::percent, limits = c(0,0.6)) +
  theme_minimal(base_size = 16) +
  theme(legend.position = "") +
  xlab("Peptide length") +
  ylab("Percentage of peptides") +
  #scale_fill_brewer(palette="Set1") +
  scale_fill_manual(values = my_cols[c(1,3)]) +
  facet_wrap(~ exp_type)
```

]]
---


